# Generated by Django 4.1 on 2022-11-08 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_about_us_text2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about_us',
            old_name='text',
            new_name='textssssssss',
        ),
    ]
