# Generated by Django 4.1.2 on 2022-11-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManClothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='')),
                ('type_clothing', models.CharField(choices=[('Jeans', 'Jeans'), ('T-Shirt', 'T-Shirt'), ('Houdey', 'Houdey'), ('Pullower', 'Pullower'), ('Suit', 'Suit')], max_length=60)),
            ],
        ),
    ]
